<?php
/**
 * Amenagement
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fei\Gael\Model;
use \Fei\Gael\ObjectSerializer;

/**
 * Amenagement Class Doc Comment
 *
 * @category Class
 * @description aménagement spécifique demandé pour le candidat * &#x60;TIER&#x60; - Temps supplémentaire temps majoré d’un 1/3 * &#x60;PAUS&#x60; - Temps supplémentaire pause * &#x60;SADE&#x60; - Salle d’examen dédiée * &#x60;SJDE&#x60; - Surveillant et jury d’examinateurs dédiés * &#x60;SECR&#x60; - Secrétaire de séance * &#x60;BRAI&#x60; - Besoin de sujets en braille (compléter l&#39;inscription 2 mois avant pour bonne réception)
 * @package  Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Amenagement
{
    /**
     * Possible values of this enum
     */
    const TIER = 'TIER';
    const PAUS = 'PAUS';
    const SADE = 'SADE';
    const SJDE = 'SJDE';
    const SECR = 'SECR';
    const BRAI = 'BRAI';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TIER,
            self::PAUS,
            self::SADE,
            self::SJDE,
            self::SECR,
            self::BRAI,
        ];
    }
}


