<?php
/**
 * CandidatSimple
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fei\Gael\Model;

use \ArrayAccess;
use \Fei\Gael\ObjectSerializer;

/**
 * CandidatSimple Class Doc Comment
 *
 * @category Class
 * @description Donnnées du candidats sans les informations d&#39;état civil, avec ses résultats à un examen donné et le montant qu&#39;il doit payé au centre.
 * @package  Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class CandidatSimple implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CandidatSimple';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'numero' => 'string',
        'nom' => 'string',
        'prenom' => 'string',
        'dateNaissance' => '\DateTime',
        'anneeNaissance' => 'int',
        'anneeNaissanceInconnue' => 'bool',
        'motif' => '\Fei\Gael\Model\MotifInscription',
        'frais' => 'float',
        'devise' => '\Fei\Gael\Model\Devise',
        'origine' => 'string',
        'reduction' => '\Fei\Gael\Model\CritereReduction',
        'handicap' => 'bool',
        'amenagement' => '\Fei\Gael\Model\Amenagement[]',
        'dispenses' => '\Fei\Gael\Model\EpreuveType[]',
        'resultats' => '\Fei\Gael\Model\Resultat[]',
        'isAdmis' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'numero' => null,
        'nom' => null,
        'prenom' => null,
        'dateNaissance' => 'date',
        'anneeNaissance' => null,
        'anneeNaissanceInconnue' => null,
        'motif' => null,
        'frais' => null,
        'devise' => null,
        'origine' => null,
        'reduction' => null,
        'handicap' => null,
        'amenagement' => null,
        'dispenses' => null,
        'resultats' => null,
        'isAdmis' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'numero' => 'numero',
        'nom' => 'nom',
        'prenom' => 'prenom',
        'dateNaissance' => 'dateNaissance',
        'anneeNaissance' => 'anneeNaissance',
        'anneeNaissanceInconnue' => 'anneeNaissanceInconnue',
        'motif' => 'motif',
        'frais' => 'frais',
        'devise' => 'devise',
        'origine' => 'origine',
        'reduction' => 'reduction',
        'handicap' => 'handicap',
        'amenagement' => 'amenagement',
        'dispenses' => 'dispenses',
        'resultats' => 'resultats',
        'isAdmis' => 'isAdmis'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'numero' => 'setNumero',
        'nom' => 'setNom',
        'prenom' => 'setPrenom',
        'dateNaissance' => 'setDateNaissance',
        'anneeNaissance' => 'setAnneeNaissance',
        'anneeNaissanceInconnue' => 'setAnneeNaissanceInconnue',
        'motif' => 'setMotif',
        'frais' => 'setFrais',
        'devise' => 'setDevise',
        'origine' => 'setOrigine',
        'reduction' => 'setReduction',
        'handicap' => 'setHandicap',
        'amenagement' => 'setAmenagement',
        'dispenses' => 'setDispenses',
        'resultats' => 'setResultats',
        'isAdmis' => 'setIsAdmis'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'numero' => 'getNumero',
        'nom' => 'getNom',
        'prenom' => 'getPrenom',
        'dateNaissance' => 'getDateNaissance',
        'anneeNaissance' => 'getAnneeNaissance',
        'anneeNaissanceInconnue' => 'getAnneeNaissanceInconnue',
        'motif' => 'getMotif',
        'frais' => 'getFrais',
        'devise' => 'getDevise',
        'origine' => 'getOrigine',
        'reduction' => 'getReduction',
        'handicap' => 'getHandicap',
        'amenagement' => 'getAmenagement',
        'dispenses' => 'getDispenses',
        'resultats' => 'getResultats',
        'isAdmis' => 'getIsAdmis'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['numero'] = $data['numero'] ?? null;
        $this->container['nom'] = $data['nom'] ?? null;
        $this->container['prenom'] = $data['prenom'] ?? null;
        $this->container['dateNaissance'] = $data['dateNaissance'] ?? null;
        $this->container['anneeNaissance'] = $data['anneeNaissance'] ?? null;
        $this->container['anneeNaissanceInconnue'] = $data['anneeNaissanceInconnue'] ?? null;
        $this->container['motif'] = $data['motif'] ?? null;
        $this->container['frais'] = $data['frais'] ?? null;
        $this->container['devise'] = $data['devise'] ?? null;
        $this->container['origine'] = $data['origine'] ?? null;
        $this->container['reduction'] = $data['reduction'] ?? null;
        $this->container['handicap'] = $data['handicap'] ?? null;
        $this->container['amenagement'] = $data['amenagement'] ?? null;
        $this->container['dispenses'] = $data['dispenses'] ?? null;
        $this->container['resultats'] = $data['resultats'] ?? null;
        $this->container['isAdmis'] = $data['isAdmis'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['numero'] === null) {
            $invalidProperties[] = "'numero' can't be null";
        }
        if ($this->container['nom'] === null) {
            $invalidProperties[] = "'nom' can't be null";
        }
        if (!is_null($this->container['frais']) && ($this->container['frais'] < 0)) {
            $invalidProperties[] = "invalid value for 'frais', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets numero
     *
     * @return string
     */
    public function getNumero()
    {
        return $this->container['numero'];
    }

    /**
     * Sets numero
     *
     * @param string $numero Numéro du candidat dans GAEL, unique.
     *
     * @return self
     */
    public function setNumero($numero)
    {
        $this->container['numero'] = $numero;

        return $this;
    }

    /**
     * Gets nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->container['nom'];
    }

    /**
     * Sets nom
     *
     * @param string $nom Nom de famille du candidat
     *
     * @return self
     */
    public function setNom($nom)
    {
        $this->container['nom'] = $nom;

        return $this;
    }

    /**
     * Gets prenom
     *
     * @return string|null
     */
    public function getPrenom()
    {
        return $this->container['prenom'];
    }

    /**
     * Sets prenom
     *
     * @param string|null $prenom Prénom du candidat
     *
     * @return self
     */
    public function setPrenom($prenom)
    {
        $this->container['prenom'] = $prenom;

        return $this;
    }

    /**
     * Gets dateNaissance
     *
     * @return \DateTime|null
     */
    public function getDateNaissance()
    {
        return $this->container['dateNaissance'];
    }

    /**
     * Sets dateNaissance
     *
     * @param \DateTime|null $dateNaissance Date de naissance du candidat
     *
     * @return self
     */
    public function setDateNaissance($dateNaissance)
    {
        $this->container['dateNaissance'] = $dateNaissance;

        return $this;
    }

    /**
     * Gets anneeNaissance
     *
     * @return int|null
     */
    public function getAnneeNaissance()
    {
        return $this->container['anneeNaissance'];
    }

    /**
     * Sets anneeNaissance
     *
     * @param int|null $anneeNaissance Année de naissance du candidat. Renseignée si elle est connue mais qu'on ne connait pas la date exacte.
     *
     * @return self
     */
    public function setAnneeNaissance($anneeNaissance)
    {
        $this->container['anneeNaissance'] = $anneeNaissance;

        return $this;
    }

    /**
     * Gets anneeNaissanceInconnue
     *
     * @return bool|null
     */
    public function getAnneeNaissanceInconnue()
    {
        return $this->container['anneeNaissanceInconnue'];
    }

    /**
     * Sets anneeNaissanceInconnue
     *
     * @param bool|null $anneeNaissanceInconnue Si le candidat ne connait ni sa date, ni son année de naissance, ce flag doit être à true
     *
     * @return self
     */
    public function setAnneeNaissanceInconnue($anneeNaissanceInconnue)
    {
        $this->container['anneeNaissanceInconnue'] = $anneeNaissanceInconnue;

        return $this;
    }

    /**
     * Gets motif
     *
     * @return \Fei\Gael\Model\MotifInscription|null
     */
    public function getMotif()
    {
        return $this->container['motif'];
    }

    /**
     * Sets motif
     *
     * @param \Fei\Gael\Model\MotifInscription|null $motif motif
     *
     * @return self
     */
    public function setMotif($motif)
    {
        $this->container['motif'] = $motif;

        return $this;
    }

    /**
     * Gets frais
     *
     * @return float|null
     */
    public function getFrais()
    {
        return $this->container['frais'];
    }

    /**
     * Sets frais
     *
     * @param float|null $frais frais
     *
     * @return self
     */
    public function setFrais($frais)
    {

        if (!is_null($frais) && ($frais < 0)) {
            throw new \InvalidArgumentException('invalid value for $frais when calling CandidatSimple., must be bigger than or equal to 0.');
        }

        $this->container['frais'] = $frais;

        return $this;
    }

    /**
     * Gets devise
     *
     * @return \Fei\Gael\Model\Devise|null
     */
    public function getDevise()
    {
        return $this->container['devise'];
    }

    /**
     * Sets devise
     *
     * @param \Fei\Gael\Model\Devise|null $devise devise
     *
     * @return self
     */
    public function setDevise($devise)
    {
        $this->container['devise'] = $devise;

        return $this;
    }

    /**
     * Gets origine
     *
     * @return string|null
     */
    public function getOrigine()
    {
        return $this->container['origine'];
    }

    /**
     * Sets origine
     *
     * @param string|null $origine code du centre d'origine / établissement partenaire / établissement affilié du candidat
     *
     * @return self
     */
    public function setOrigine($origine)
    {
        $this->container['origine'] = $origine;

        return $this;
    }

    /**
     * Gets reduction
     *
     * @return \Fei\Gael\Model\CritereReduction|null
     */
    public function getReduction()
    {
        return $this->container['reduction'];
    }

    /**
     * Sets reduction
     *
     * @param \Fei\Gael\Model\CritereReduction|null $reduction reduction
     *
     * @return self
     */
    public function setReduction($reduction)
    {
        $this->container['reduction'] = $reduction;

        return $this;
    }

    /**
     * Gets handicap
     *
     * @return bool|null
     */
    public function getHandicap()
    {
        return $this->container['handicap'];
    }

    /**
     * Sets handicap
     *
     * @param bool|null $handicap le candidat a un handicap ou non
     *
     * @return self
     */
    public function setHandicap($handicap)
    {
        $this->container['handicap'] = $handicap;

        return $this;
    }

    /**
     * Gets amenagement
     *
     * @return \Fei\Gael\Model\Amenagement[]|null
     */
    public function getAmenagement()
    {
        return $this->container['amenagement'];
    }

    /**
     * Sets amenagement
     *
     * @param \Fei\Gael\Model\Amenagement[]|null $amenagement amenagement
     *
     * @return self
     */
    public function setAmenagement($amenagement)
    {
        $this->container['amenagement'] = $amenagement;

        return $this;
    }

    /**
     * Gets dispenses
     *
     * @return \Fei\Gael\Model\EpreuveType[]|null
     */
    public function getDispenses()
    {
        return $this->container['dispenses'];
    }

    /**
     * Sets dispenses
     *
     * @param \Fei\Gael\Model\EpreuveType[]|null $dispenses dispenses
     *
     * @return self
     */
    public function setDispenses($dispenses)
    {
        $this->container['dispenses'] = $dispenses;

        return $this;
    }

    /**
     * Gets resultats
     *
     * @return \Fei\Gael\Model\Resultat[]|null
     */
    public function getResultats()
    {
        return $this->container['resultats'];
    }

    /**
     * Sets resultats
     *
     * @param \Fei\Gael\Model\Resultat[]|null $resultats résultats du candidat à l'examen
     *
     * @return self
     */
    public function setResultats($resultats)
    {
        $this->container['resultats'] = $resultats;

        return $this;
    }

    /**
     * Gets isAdmis
     *
     * @return bool|null
     */
    public function getIsAdmis()
    {
        return $this->container['isAdmis'];
    }

    /**
     * Sets isAdmis
     *
     * @param bool|null $isAdmis indique si le candidat a réussi son examen
     *
     * @return self
     */
    public function setIsAdmis($isAdmis)
    {
        $this->container['isAdmis'] = $isAdmis;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


