<?php
/**
 * CandidatCreation
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fei\Gael\Model;

use \ArrayAccess;
use \Fei\Gael\ObjectSerializer;

/**
 * CandidatCreation Class Doc Comment
 *
 * @category Class
 * @description Donnnées d&#39;un nouveau candidat pour l&#39;enregistrer dans GAEL. Le codeCentre renseigne le centre de rattachement de tous les candidats de la liste. Pour inscrire des candidats rattachés à différents centres, faire un appel par centre. Un et un seul des trois champs suivants doit être rempli : &#39;dateNaissance&#39;, &#39;anneeNaissance&#39;, &#39;anneeNaissanceInconnue&#39;
 * @package  Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class CandidatCreation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CandidatCreation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'civilite' => '\Fei\Gael\Model\Civilite',
        'nom' => 'string',
        'patronyme' => 'string',
        'prenom' => 'string',
        'dateNaissance' => '\DateTime',
        'anneeNaissance' => 'int',
        'anneeNaissanceInconnue' => 'bool',
        'paysNaissance' => '\Fei\Gael\Model\Pays',
        'villeNaissance' => 'string',
        'nationalite1' => '\Fei\Gael\Model\Nationalite',
        'nationalite2' => '\Fei\Gael\Model\Nationalite',
        'langueMaternelle' => '\Fei\Gael\Model\Langue',
        'adresse1' => '\Fei\Gael\Model\AdressePostale',
        'adresse2' => '\Fei\Gael\Model\AdressePostale',
        'telephone1' => '\Fei\Gael\Model\Telephone',
        'telephone2' => '\Fei\Gael\Model\Telephone',
        'courriel' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'civilite' => null,
        'nom' => null,
        'patronyme' => null,
        'prenom' => null,
        'dateNaissance' => 'date',
        'anneeNaissance' => null,
        'anneeNaissanceInconnue' => null,
        'paysNaissance' => null,
        'villeNaissance' => null,
        'nationalite1' => null,
        'nationalite2' => null,
        'langueMaternelle' => null,
        'adresse1' => null,
        'adresse2' => null,
        'telephone1' => null,
        'telephone2' => null,
        'courriel' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'civilite' => 'civilite',
        'nom' => 'nom',
        'patronyme' => 'patronyme',
        'prenom' => 'prenom',
        'dateNaissance' => 'dateNaissance',
        'anneeNaissance' => 'anneeNaissance',
        'anneeNaissanceInconnue' => 'anneeNaissanceInconnue',
        'paysNaissance' => 'paysNaissance',
        'villeNaissance' => 'villeNaissance',
        'nationalite1' => 'nationalite1',
        'nationalite2' => 'nationalite2',
        'langueMaternelle' => 'langueMaternelle',
        'adresse1' => 'adresse1',
        'adresse2' => 'adresse2',
        'telephone1' => 'telephone1',
        'telephone2' => 'telephone2',
        'courriel' => 'courriel'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'civilite' => 'setCivilite',
        'nom' => 'setNom',
        'patronyme' => 'setPatronyme',
        'prenom' => 'setPrenom',
        'dateNaissance' => 'setDateNaissance',
        'anneeNaissance' => 'setAnneeNaissance',
        'anneeNaissanceInconnue' => 'setAnneeNaissanceInconnue',
        'paysNaissance' => 'setPaysNaissance',
        'villeNaissance' => 'setVilleNaissance',
        'nationalite1' => 'setNationalite1',
        'nationalite2' => 'setNationalite2',
        'langueMaternelle' => 'setLangueMaternelle',
        'adresse1' => 'setAdresse1',
        'adresse2' => 'setAdresse2',
        'telephone1' => 'setTelephone1',
        'telephone2' => 'setTelephone2',
        'courriel' => 'setCourriel'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'civilite' => 'getCivilite',
        'nom' => 'getNom',
        'patronyme' => 'getPatronyme',
        'prenom' => 'getPrenom',
        'dateNaissance' => 'getDateNaissance',
        'anneeNaissance' => 'getAnneeNaissance',
        'anneeNaissanceInconnue' => 'getAnneeNaissanceInconnue',
        'paysNaissance' => 'getPaysNaissance',
        'villeNaissance' => 'getVilleNaissance',
        'nationalite1' => 'getNationalite1',
        'nationalite2' => 'getNationalite2',
        'langueMaternelle' => 'getLangueMaternelle',
        'adresse1' => 'getAdresse1',
        'adresse2' => 'getAdresse2',
        'telephone1' => 'getTelephone1',
        'telephone2' => 'getTelephone2',
        'courriel' => 'getCourriel'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['civilite'] = $data['civilite'] ?? null;
        $this->container['nom'] = $data['nom'] ?? null;
        $this->container['patronyme'] = $data['patronyme'] ?? null;
        $this->container['prenom'] = $data['prenom'] ?? null;
        $this->container['dateNaissance'] = $data['dateNaissance'] ?? null;
        $this->container['anneeNaissance'] = $data['anneeNaissance'] ?? null;
        $this->container['anneeNaissanceInconnue'] = $data['anneeNaissanceInconnue'] ?? null;
        $this->container['paysNaissance'] = $data['paysNaissance'] ?? null;
        $this->container['villeNaissance'] = $data['villeNaissance'] ?? null;
        $this->container['nationalite1'] = $data['nationalite1'] ?? null;
        $this->container['nationalite2'] = $data['nationalite2'] ?? null;
        $this->container['langueMaternelle'] = $data['langueMaternelle'] ?? null;
        $this->container['adresse1'] = $data['adresse1'] ?? null;
        $this->container['adresse2'] = $data['adresse2'] ?? null;
        $this->container['telephone1'] = $data['telephone1'] ?? null;
        $this->container['telephone2'] = $data['telephone2'] ?? null;
        $this->container['courriel'] = $data['courriel'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['nom'] === null) {
            $invalidProperties[] = "'nom' can't be null";
        }
        if ($this->container['paysNaissance'] === null) {
            $invalidProperties[] = "'paysNaissance' can't be null";
        }
        if ($this->container['villeNaissance'] === null) {
            $invalidProperties[] = "'villeNaissance' can't be null";
        }
        if ($this->container['nationalite1'] === null) {
            $invalidProperties[] = "'nationalite1' can't be null";
        }
        if ($this->container['langueMaternelle'] === null) {
            $invalidProperties[] = "'langueMaternelle' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets civilite
     *
     * @return \Fei\Gael\Model\Civilite|null
     */
    public function getCivilite()
    {
        return $this->container['civilite'];
    }

    /**
     * Sets civilite
     *
     * @param \Fei\Gael\Model\Civilite|null $civilite civilite
     *
     * @return self
     */
    public function setCivilite($civilite)
    {
        $this->container['civilite'] = $civilite;

        return $this;
    }

    /**
     * Gets nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->container['nom'];
    }

    /**
     * Sets nom
     *
     * @param string $nom Nom de famille du candidat
     *
     * @return self
     */
    public function setNom($nom)
    {
        $this->container['nom'] = $nom;

        return $this;
    }

    /**
     * Gets patronyme
     *
     * @return string|null
     */
    public function getPatronyme()
    {
        return $this->container['patronyme'];
    }

    /**
     * Sets patronyme
     *
     * @param string|null $patronyme Patronyme du candidat
     *
     * @return self
     */
    public function setPatronyme($patronyme)
    {
        $this->container['patronyme'] = $patronyme;

        return $this;
    }

    /**
     * Gets prenom
     *
     * @return string|null
     */
    public function getPrenom()
    {
        return $this->container['prenom'];
    }

    /**
     * Sets prenom
     *
     * @param string|null $prenom Prénom du candidat
     *
     * @return self
     */
    public function setPrenom($prenom)
    {
        $this->container['prenom'] = $prenom;

        return $this;
    }

    /**
     * Gets dateNaissance
     *
     * @return \DateTime|null
     */
    public function getDateNaissance()
    {
        return $this->container['dateNaissance'];
    }

    /**
     * Sets dateNaissance
     *
     * @param \DateTime|null $dateNaissance date de naissance du candidat
     *
     * @return self
     */
    public function setDateNaissance($dateNaissance)
    {
        $this->container['dateNaissance'] = $dateNaissance;

        return $this;
    }

    /**
     * Gets anneeNaissance
     *
     * @return int|null
     */
    public function getAnneeNaissance()
    {
        return $this->container['anneeNaissance'];
    }

    /**
     * Sets anneeNaissance
     *
     * @param int|null $anneeNaissance l'année de naissance du candidat si sa date de naissance n'est pas connue
     *
     * @return self
     */
    public function setAnneeNaissance($anneeNaissance)
    {
        $this->container['anneeNaissance'] = $anneeNaissance;

        return $this;
    }

    /**
     * Gets anneeNaissanceInconnue
     *
     * @return bool|null
     */
    public function getAnneeNaissanceInconnue()
    {
        return $this->container['anneeNaissanceInconnue'];
    }

    /**
     * Sets anneeNaissanceInconnue
     *
     * @param bool|null $anneeNaissanceInconnue si le candidat ne connait ni sa date, ni son année de naissance, ce flag doit être à true
     *
     * @return self
     */
    public function setAnneeNaissanceInconnue($anneeNaissanceInconnue)
    {
        $this->container['anneeNaissanceInconnue'] = $anneeNaissanceInconnue;

        return $this;
    }

    /**
     * Gets paysNaissance
     *
     * @return \Fei\Gael\Model\Pays
     */
    public function getPaysNaissance()
    {
        return $this->container['paysNaissance'];
    }

    /**
     * Sets paysNaissance
     *
     * @param \Fei\Gael\Model\Pays $paysNaissance paysNaissance
     *
     * @return self
     */
    public function setPaysNaissance($paysNaissance)
    {
        $this->container['paysNaissance'] = $paysNaissance;

        return $this;
    }

    /**
     * Gets villeNaissance
     *
     * @return string
     */
    public function getVilleNaissance()
    {
        return $this->container['villeNaissance'];
    }

    /**
     * Sets villeNaissance
     *
     * @param string $villeNaissance Ville de naissance du candidat
     *
     * @return self
     */
    public function setVilleNaissance($villeNaissance)
    {
        $this->container['villeNaissance'] = $villeNaissance;

        return $this;
    }

    /**
     * Gets nationalite1
     *
     * @return \Fei\Gael\Model\Nationalite
     */
    public function getNationalite1()
    {
        return $this->container['nationalite1'];
    }

    /**
     * Sets nationalite1
     *
     * @param \Fei\Gael\Model\Nationalite $nationalite1 nationalite1
     *
     * @return self
     */
    public function setNationalite1($nationalite1)
    {
        $this->container['nationalite1'] = $nationalite1;

        return $this;
    }

    /**
     * Gets nationalite2
     *
     * @return \Fei\Gael\Model\Nationalite|null
     */
    public function getNationalite2()
    {
        return $this->container['nationalite2'];
    }

    /**
     * Sets nationalite2
     *
     * @param \Fei\Gael\Model\Nationalite|null $nationalite2 nationalite2
     *
     * @return self
     */
    public function setNationalite2($nationalite2)
    {
        $this->container['nationalite2'] = $nationalite2;

        return $this;
    }

    /**
     * Gets langueMaternelle
     *
     * @return \Fei\Gael\Model\Langue
     */
    public function getLangueMaternelle()
    {
        return $this->container['langueMaternelle'];
    }

    /**
     * Sets langueMaternelle
     *
     * @param \Fei\Gael\Model\Langue $langueMaternelle langueMaternelle
     *
     * @return self
     */
    public function setLangueMaternelle($langueMaternelle)
    {
        $this->container['langueMaternelle'] = $langueMaternelle;

        return $this;
    }

    /**
     * Gets adresse1
     *
     * @return \Fei\Gael\Model\AdressePostale|null
     */
    public function getAdresse1()
    {
        return $this->container['adresse1'];
    }

    /**
     * Sets adresse1
     *
     * @param \Fei\Gael\Model\AdressePostale|null $adresse1 adresse1
     *
     * @return self
     */
    public function setAdresse1($adresse1)
    {
        $this->container['adresse1'] = $adresse1;

        return $this;
    }

    /**
     * Gets adresse2
     *
     * @return \Fei\Gael\Model\AdressePostale|null
     */
    public function getAdresse2()
    {
        return $this->container['adresse2'];
    }

    /**
     * Sets adresse2
     *
     * @param \Fei\Gael\Model\AdressePostale|null $adresse2 adresse2
     *
     * @return self
     */
    public function setAdresse2($adresse2)
    {
        $this->container['adresse2'] = $adresse2;

        return $this;
    }

    /**
     * Gets telephone1
     *
     * @return \Fei\Gael\Model\Telephone|null
     */
    public function getTelephone1()
    {
        return $this->container['telephone1'];
    }

    /**
     * Sets telephone1
     *
     * @param \Fei\Gael\Model\Telephone|null $telephone1 telephone1
     *
     * @return self
     */
    public function setTelephone1($telephone1)
    {
        $this->container['telephone1'] = $telephone1;

        return $this;
    }

    /**
     * Gets telephone2
     *
     * @return \Fei\Gael\Model\Telephone|null
     */
    public function getTelephone2()
    {
        return $this->container['telephone2'];
    }

    /**
     * Sets telephone2
     *
     * @param \Fei\Gael\Model\Telephone|null $telephone2 telephone2
     *
     * @return self
     */
    public function setTelephone2($telephone2)
    {
        $this->container['telephone2'] = $telephone2;

        return $this;
    }

    /**
     * Gets courriel
     *
     * @return string|null
     */
    public function getCourriel()
    {
        return $this->container['courriel'];
    }

    /**
     * Sets courriel
     *
     * @param string|null $courriel Un email de contact du candidat
     *
     * @return self
     */
    public function setCourriel($courriel)
    {
        $this->container['courriel'] = $courriel;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


