<?php
/**
 * CritereReduction
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fei\Gael\Model;
use \Fei\Gael\ObjectSerializer;

/**
 * CritereReduction Class Doc Comment
 *
 * @category Class
 * @description Un candidat peut recevoir une réduction parmie une liste pré-définie par FEI * C1    Réduction pour apprenant de la structure * C2    Réduction pour apprenant d&#39;organismes partenaires (éducatif élémentaire) * C3    Réduction pour apprenant d&#39;organismes partenaires (éducatif secondaire) * C4    Réduction pour apprenant d&#39;organismes partenaires (établissements d&#39;enseignement supérieur) * C5    Réduction pour apprenant d&#39;organismes partenaires (administrations publiques) * C6    Réduction pour enseignant de français * C7    Réduction dans le cadre d&#39;un tarif de group
 * @package  Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CritereReduction
{
    /**
     * Possible values of this enum
     */
    const C1 = 'C1';
    const C2 = 'C2';
    const C3 = 'C3';
    const C4 = 'C4';
    const C5 = 'C5';
    const C6 = 'C6';
    const C7 = 'C7';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::C1,
            self::C2,
            self::C3,
            self::C4,
            self::C5,
            self::C6,
            self::C7,
        ];
    }
}


