<?php
/**
 * NiveauExamen
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fei\Gael\Model;
use \Fei\Gael\ObjectSerializer;

/**
 * NiveauExamen Class Doc Comment
 *
 * @category Class
 * @description Niveau d&#39;un examen selon la norme européenne.
 * @package  Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NiveauExamen
{
    /**
     * Possible values of this enum
     */
    const A1_1 = 'A1.1';
    const A1 = 'A1';
    const A2 = 'A2';
    const B1 = 'B1';
    const B2 = 'B2';
    const C1 = 'C1';
    const C2 = 'C2';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::A1_1,
            self::A1,
            self::A2,
            self::B1,
            self::B2,
            self::C1,
            self::C2,
        ];
    }
}


