<?php
/**
 * AmenagementTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Inflexyon\Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Inflexyon\Fei\Gael\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AmenagementTest Class Doc Comment
 *
 * @category    Class
 * @description aménagement spécifique demandé pour le candidat * &#x60;TIER&#x60; - Temps supplémentaire temps majoré d’un 1/3 * &#x60;PAUS&#x60; - Temps supplémentaire pause * &#x60;SADE&#x60; - Salle d’examen dédiée * &#x60;SJDE&#x60; - Surveillant et jury d’examinateurs dédiés * &#x60;SECR&#x60; - Secrétaire de séance * &#x60;BRAI&#x60; - Besoin de sujets en braille (compléter l&#39;inscription 2 mois avant pour bonne réception)
 * @package     Inflexyon\Fei\Gael
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AmenagementTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Amenagement"
     */
    public function testAmenagement()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
