<?php
/**
 * CandidatCreeTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Inflexyon\Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Inflexyon\Fei\Gael\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CandidatCreeTest Class Doc Comment
 *
 * @category    Class
 * @description Le candidat nouvellement créé dans GAEL renvoyé suite à un appel POST à /examen/addCandidats. Contient le numéro unique plus les informations nécessaires pour identifier de façon unique un candidat. Si il n&#39;y a pas de numéro de candidat, c&#39;est que GAEL a détecté un doublon pour le nom, prénom et date/année de naissance renseignés. Le flag isDoublon est alors à true.
 * @package     Inflexyon\Fei\Gael
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CandidatCreeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CandidatCree"
     */
    public function testCandidatCree()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isDoublon"
     */
    public function testPropertyIsDoublon()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numeroCandidat"
     */
    public function testPropertyNumeroCandidat()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nom"
     */
    public function testPropertyNom()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "prenom"
     */
    public function testPropertyPrenom()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dateNaissance"
     */
    public function testPropertyDateNaissance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "anneeNaissance"
     */
    public function testPropertyAnneeNaissance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "anneeNaissanceInconnue"
     */
    public function testPropertyAnneeNaissanceInconnue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
