<?php
/**
 * CritereReductionTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Inflexyon\Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Inflexyon\Fei\Gael\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CritereReductionTest Class Doc Comment
 *
 * @category    Class
 * @description Un candidat peut recevoir une réduction parmie une liste pré-définie par FEI * C1    Réduction pour apprenant de la structure * C2    Réduction pour apprenant d&#39;organismes partenaires (éducatif élémentaire) * C3    Réduction pour apprenant d&#39;organismes partenaires (éducatif secondaire) * C4    Réduction pour apprenant d&#39;organismes partenaires (établissements d&#39;enseignement supérieur) * C5    Réduction pour apprenant d&#39;organismes partenaires (administrations publiques) * C6    Réduction pour enseignant de français * C7    Réduction dans le cadre d&#39;un tarif de group
 * @package     Inflexyon\Fei\Gael
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CritereReductionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CritereReduction"
     */
    public function testCritereReduction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
