<?php
/**
 * EpreuveTypeTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Inflexyon\Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Inflexyon\Fei\Gael\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EpreuveTypeTest Class Doc Comment
 *
 * @category    Class
 * @description type de resultat * &#x60;CO&#x60; - Compréhension oral * &#x60;CE&#x60; - Compréhension écrite * &#x60;PO&#x60; - Production oral * &#x60;PE&#x60; - Production écrite * &#x60;EE&#x60; - Compréhension et production écrite * &#x60;EO&#x60; - Compréhension et productions orales * &#x60;TO&#x60; - Note globale * &#x60;FI&#x60; - Note finale après revalorisation du jury
 * @package     Inflexyon\Fei\Gael
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EpreuveTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EpreuveType"
     */
    public function testEpreuveType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
