<?php
/**
 * MotifInscriptionTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Inflexyon\Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Inflexyon\Fei\Gael\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MotifInscriptionTest Class Doc Comment
 *
 * @category    Class
 * @description motif de l&#39;inscription du candidat * &#x60;ECOL&#x60; - Ecole/études dans le pays d’origine * &#x60;ETFR&#x60; - Mobilité étudiante vers la France * &#x60;ETAU&#x60; - Mobilité étudiante vers d’autres pays francophones * &#x60;ACNA&#x60; - Acquisition de la nationalité * &#x60;PROF&#x60; - Besoins professionnels * &#x60;MIFR&#x60; - Projet de migration vers la France * &#x60;MIAU&#x60; - Projet de migration vers d’autres pays francophones * &#x60;PERS&#x60; - Motivation personnelle
 * @package     Inflexyon\Fei\Gael
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MotifInscriptionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MotifInscription"
     */
    public function testMotifInscription()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
