<?php
/**
 * PaysTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Inflexyon\Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Inflexyon\Fei\Gael\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PaysTest Class Doc Comment
 *
 * @category    Class
 * @description L&#39;objet PAYS exposé par GAEL est défini par son code pays GAEL, son code ISO 3, son libellé usuel et son libellé diplomatique.
 * @package     Inflexyon\Fei\Gael
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaysTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Pays"
     */
    public function testPays()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "codeIso3"
     */
    public function testPropertyCodeIso3()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "libelle"
     */
    public function testPropertyLibelle()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "libelleLong"
     */
    public function testPropertyLibelleLong()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
