<?php
/**
 * ResultatTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Inflexyon\Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Inflexyon\Fei\Gael\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ResultatTest Class Doc Comment
 *
 * @category    Class
 * @description Note (ou absence ou dispense) pour 1 épreuve d&#39;1 examen. GAEL vérifie la cohérence des données soumises. Les notes vont de 0.5 en 0.5 points entre 0 et 25 inclus, sauf pour le C2 qui va jusqu&#39;à 50.
 * @package     Inflexyon\Fei\Gael
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ResultatTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Resultat"
     */
    public function testResultat()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "typeResultat"
     */
    public function testPropertyTypeResultat()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statut"
     */
    public function testPropertyStatut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
