<?php
/**
 * UploadedResultsResultatsTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Inflexyon\Fei\Gael
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GAEL API
 *
 * Ceci est l'API des web services exposés par le système informatique GAEL (Gestion Administrative En Ligne) pour France Éducation international.  Cette API offre les services suivants   * inscrire un ou plusieurs candidats à un examen  * importer dans GAEL les résultats d'un ou plusieurs candidats à un même examen
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: gael-api@france-education-international.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Inflexyon\Fei\Gael\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UploadedResultsResultatsTest Class Doc Comment
 *
 * @category    Class
 * @description Résultats d&#39;un candidat ayant participé à cet examen
 * @package     Inflexyon\Fei\Gael
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UploadedResultsResultatsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UploadedResultsResultats"
     */
    public function testUploadedResultsResultats()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero"
     */
    public function testPropertyNumero()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "resultats"
     */
    public function testPropertyResultats()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
